---
title: "Data Science for Bioinformatics - Week 02 R for datascience"
output: 
  html_document:
    code_folding: show
    toc: yes
editor_options: 
  chunk_output_type: console
---

4.4.1
```{r}
my_variable <- 10
my_variable
```

4.4.2
```{r}
library(tidyverse)

ggplot(mpg) +
    geom_point(mapping = aes(x = displ, y = hwy))

filter(mpg, cyl == 8)
filter(diamonds, carat > 3)
```
4.4.3

5.2.4.1
```{r}
flights %>%
    filter(arr_delay >= 120)
flights %>%
    filter(dest %in% c("IAH", "HOU"))
flights %>%
    filter(carrier %in% c("UA", "AA", "DL"))
flights %>%
    filter(month %in% c(7, 8, 9))
flights %>%
    filter(arr_delay > dep_delay + 120)
flights %>%
    filter(dep_delay >= 60, arr_delay <= 30)
flights %>%
    filter(hour >= 0 & hour <= 6)
```
5.2.4.2
yes
5.2.4.3
```{r}
flights %>% filter(is.na(dep_time))
```
8255
5.2.4.4
```{r}
NA^0
```


5.3.1.1

```{r}
# Sort the mtcars dataset by mpg, with missing values first
arrange(flights, desc(is.na(dep_delay)), dep_delay)
```

5.3.1.2
```{r}

```
5.3.1.3
```{r}

```
5.3.1.4
```{r}

```



