---
title: "Data Science for Bioinformatics - Week 01 R for datascience"
output: 
  html_document:
    code_folding: show
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
```


3.2.4.1
```{r}
ggplot(mpg)
```

3.2.4.2
```{r}
nrow(mpg)
```

3.2.4.3
drv
the type of drive train, where f = front-wheel drive, r = rear wheel drive, 4 = 4wd
3.2.4.4
```{r}
ggplot(data = mpg) +
    geom_point(mapping = aes(x = cyl, y = hwy))
```
3.2.4.5
```{r}
ggplot(data = mpg) +
    geom_point(mapping = aes(x = class, y = drv))
```


3.3.1.1
```{r}
ggplot(data = mpg) +
    geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

3.3.1.2
```{r}
summary(mpg)
```

3.3.1.3
```{r}
ggplot(data = mpg) +
    geom_point(mapping = aes(x = displ, y = hwy, shape = model, size = class, color = drv), stroke = 2)
```




3.7.1.1

```{r}
ggplot(data = diamonds) +
    stat_summary(
        mapping = aes(x = cut, y = depth),
        fun.min = min,
        fun.max = max,
        fun = median
    )
```


```{r}
ggplot(diamonds, aes(x = cut, y = depth)) +
    geom_pointrange(aes(ymin = after_stat(ymin), ymax = after_stat(ymax)), stat = "summary", fun.max = max, fun.min = min, fun = median)
```